name: CI Pipeline

# Określenie, kiedy workflow ma być uruchamiane
on:
  push:
    branches:
      - main   # Workflow uruchamia się po każdym pushu do gałęzi main
  pull_request:
    branches:
      - main   # Workflow uruchamia się przy otwieraniu pull requesta do gałęzi main

jobs:
  build:
    runs-on: ubuntu-latest  # Workflow będzie uruchamiany na najnowszej wersji Ubuntu

    steps:
      # Krok 1: Pobierz kod
      - name: Checkout code
        uses: actions/checkout@v2

      # Krok 2: Ustawienie JDK
      - name: Set Java 18
        uses: actions/setup-java@v2
        with:
          java-version: '18'  # Określamy wersję JDK
          distribution: 'temurin'  # Używamy Amazon Corretto

      # Krok 3: Zbudowanie aplikacji
      - name: Build with Maven
        run: mvn clean install -DskipTests

      # Krok 4: Uruchomienie testów jednostkowych
      - name: Run unit tests
        run: mvn test

      # Krok 4: Uruchomienie testów jednostkowych
      - name: Run integration tests
        run: mvn verify -Pintegration-tests

      # Krok 5: (opcjonalnie) Publikacja wyników testów
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: target/test-classes
